resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: httpbin_cluster
  type: STRICT_DNS
  lb_policy: round_robin
  dns_lookup_family: V4_ONLY
  load_assignment:
    cluster_name: httpbin_cluster
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: www.httpbin.org
              port_value: 443
  transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.httpbin.org